Repository Dev-FE-3/toy-project2-team2, pull requests merged in 2025-03, with the labels that each got.

#25 Feat : Header 사용자 정보 반영
  src/shared/Header/Header.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: enhancement

#23 Feat : textbox component 수정
  src/pages/guide/Guide.jsx
  src/shared/components/TextArea.jsx
  src/shared/components/TextBoxWrapper.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: enhancement

#22 Feat : input component 수정
  src/pages/guide/Guide.jsx
  src/pages/login/Login.jsx
  src/pages/login/LoginInput.jsx
  src/shared/components/Input.jsx
  src/shared/components/input/Input.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: enhancement

#26 Feat : Component(Modal, DatePicker, SelectBox)
  src/pages/guide/Guide.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/shared/components/DatePicker.jsx
  src/shared/components/SelectBox.jsx
  src/shared/components/modal/Modal.jsx
  src/shared/components/modal/useModal.jsx
Labels: enhancement

#27 Refactor : 폴더 구조 변경
  public/fonts/NotoSansKR-Black.ttf
  public/fonts/NotoSansKR-Black.woff
  public/fonts/NotoSansKR-Black.woff2
  public/fonts/NotoSansKR-Bold.ttf
  public/fonts/NotoSansKR-Bold.woff
  public/fonts/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR-ExtraBold.ttf
  public/fonts/NotoSansKR-ExtraBold.woff
  public/fonts/NotoSansKR-ExtraBold.woff2
  public/fonts/NotoSansKR-ExtraLight.ttf
  public/fonts/NotoSansKR-ExtraLight.woff
  public/fonts/NotoSansKR-ExtraLight.woff2
  public/fonts/NotoSansKR-Light.ttf
  public/fonts/NotoSansKR-Light.woff
  public/fonts/NotoSansKR-Light.woff2
  public/fonts/NotoSansKR-Medium.ttf
  public/fonts/NotoSansKR-Medium.woff
  public/fonts/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR-Regular.ttf
  public/fonts/NotoSansKR-Regular.woff
  public/fonts/NotoSansKR-Regular.woff2
  public/fonts/NotoSansKR-SemiBold.ttf
  public/fonts/NotoSansKR-SemiBold.woff
  public/fonts/NotoSansKR-SemiBold.woff2
  public/fonts/NotoSansKR-Thin.ttf
  public/fonts/NotoSansKR-Thin.woff
  public/fonts/NotoSansKR-Thin.woff2
  public/images/Down.svg
  public/images/Group.svg
  public/images/cancel.svg
  public/images/defaultImg.svg
  public/images/logo.svg
  src/App.jsx
  src/pages/guide/Guide.jsx
  src/pages/login/Login.jsx
  src/pages/mySalary/MySalary.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/shared/Header/Header.jsx
  src/shared/Header/LogOutButton.jsx
  src/shared/components/Button.jsx
  src/shared/components/DatePicker.jsx
  src/shared/components/PageTitle.jsx
  src/shared/components/ProtectedRoute.jsx
  src/shared/components/SelectBox.jsx
  src/shared/components/modal/Modal.jsx
  src/shared/components/protected-route/ProtectedRoute.jsx
  src/shared/components/styles/GlobalStyle.jsx
  src/shared/components/styles/fonts.css
  src/shared/firebase.js
Labels: enhancement

#21 Feat : Signup page
  src/App.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/auth/components/LoginInput.jsx
  src/pages/auth/components/auth-component.jsx
  src/pages/auth/constant/authErrors.js
  src/pages/auth/util/handleError.js
  src/pages/calendar/Calendar.jsx
  src/pages/guide/Guide.jsx
  src/pages/login/Login.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: feat

#31 Feat : 지급 내역 페이지
  src/pages/calendar/Calendar.jsx
  src/pages/mySalary/MySalary.jsx
  src/pages/mySalary/components/CalcBox.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: feat

#32 Feat: 정정내역/ 신청 (파이어베이스 연동)
  package-lock.json
  src/pages/guide/Guide.jsx
  src/pages/mySalary/MySalary.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/shared/components/PageTitle.jsx
  src/shared/components/modal/Modal.jsx
Labels: feat

#33 Feat : 내 일정 캘린더 페이지
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarHeader.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/IconArrow.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/pages/guide/Guide.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/shared/components/modal/Modal.jsx
Labels: feat

#29 Feat : 회원가입 입력값 추가
  src/pages/auth/Signup.jsx
  src/pages/auth/components/LoginInput.jsx
  src/pages/auth/components/auth-component.jsx
  src/shared/components/SelectBox.jsx
Labels: enhancement

#34 Style : 애니메이션 주석처리
  src/pages/calendar/components/CalendarSchedule.jsx
Labels: enhancement

#39 Style : 버튼 & 모달 컴포넌트 수정
  src/pages/calendar/components/CalendarHeader.jsx
  src/pages/guide/Guide.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/shared/components/Button.jsx
  src/shared/components/modal/Modal.jsx
Labels: enhancement

#38 Feat : Redux 적용
  package-lock.json
  package.json
  src/main.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/calendar/Calendar.jsx
  src/pages/mySalary/MySalary.jsx
  src/shared/Header/Header.jsx
  src/shared/components/TextArea.jsx
  src/store/store.js
  src/store/userSlice.js
Labels: feat

#36 Feat : 캘린더 일정 기능 추가
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarHeader.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/shared/components/DatePicker.jsx
  src/shared/components/Input.jsx
  src/shared/components/TextArea.jsx
  src/shared/components/modal/Modal.jsx
Labels: feat

#35 Feat : 정정내역/ 신청 (모달 분리
  package-lock.json
  package.json
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/SalaryHistoryModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/shared/components/SelectBox.jsx
  src/shared/components/TextArea.jsx
  src/shared/components/modal/Modal.jsx
Labels: enhancement

#44 Feat : 캘린더 기능 추가
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/shared/components/Input.jsx
  src/shared/components/TextArea.jsx
Labels: feat

#45 Feat : redux 수정
  src/pages/mySalary/MySalary.jsx
  src/shared/Header/Header.jsx
Labels: enhancement

#49 Feature/salary list admin
  public/images/reset.svg
  src/App.jsx
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/pages/employeeList/EmployeeList.jsx
  src/pages/guide/Guide.jsx
  src/pages/mySalary/SalaryAdmin.jsx
  src/pages/mySalary/components/CalcBox.jsx
  src/pages/mySalary/components/EditableCalcBox.jsx
  src/shared/components/Input.jsx
  src/shared/components/ProtectedRouteForManager.jsx
Labels: feat

#46 Feat : date picker label 추가
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarHeader.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/pages/calendar/hooks/useCalendar.js
  src/shared/components/Button.jsx
  src/shared/components/DatePicker.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: enhancement

#48 Feat : Header 프로필 등록 수정
  src/shared/Header/Header.jsx
  src/shared/components/styles/GlobalStyle.jsx
Labels: enhancement

#50 Feat : 라벨 수정 / 날짜 수정
  package-lock.json
  package.json
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/SalaryHistoryModal.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/shared/components/DatePicker.jsx
  src/shared/components/SelectBox.jsx
Labels: enhancement

#51 Fix : 로그인 인풋 라벨 수정
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/auth/components/LoginInput.jsx
  src/pages/calendar/components/ModalCalendar.jsx
  src/pages/salaryAdjustment/components/SalaryHistoryModal.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
Labels: enhancement

#52 Fix : 일정 겹치는 현상 수정
  src/pages/calendar/components/CalendarSchedule.jsx
Labels: enhancement

#54 Fix : 정정 내역/신청 페이지 모달 수정 및 회원가입 리디렉션 오류 수정
  src/pages/auth/Signup.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
Labels: enhancement

#53 Feat : toast
  src/main.jsx
  src/pages/auth/Signup.jsx
  src/pages/calendar/Calendar.jsx
  src/pages/employeeList/EmployeeList.jsx
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/shared/components/SelectBox.jsx
  src/shared/components/ToastProvider.jsx
Labels: feat

#55 Refactor : Salary 관련 hooks, utils 분리
  package-lock.json
  src/App.jsx
  src/pages/employeeList/EmployeeList.jsx
  src/pages/guide/Guide.jsx
  src/pages/mySalary/MySalary.jsx
  src/pages/mySalary/SalaryAdmin.jsx
  src/pages/mySalary/hooks/useAvailableMonths.js
  src/pages/mySalary/hooks/useRecalculateDeductions.js
  src/pages/mySalary/hooks/useSalaryData.js
  src/pages/mySalary/utils/formatHiredDate.js
  src/shared/Header/Nav.jsx
Labels: refactor

#56 Refactor : 내 일정 hooks, utils, components 분리
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarBody.jsx
  src/pages/calendar/components/CalendarCell.jsx
  src/pages/calendar/components/CalendarSchedule.jsx
  src/pages/calendar/components/ModalContent.jsx
  src/pages/calendar/components/ScheduleBar.jsx
  src/pages/calendar/hooks/useSchedules.js
  src/pages/calendar/utils/getSchedules.js
Labels: refactor

#59 Refactor : toast 적용 & router에서 훅과 컴포넌트를 분리
  src/App.jsx
  src/main.jsx
  src/pages/auth/Login.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/shared/components/router/hooks/useAuthUser.js
  src/shared/components/router/protectedRoute/ProtectedRoute.jsx
  src/shared/components/router/protectedRoute/ProtectedRouteForManager.jsx
  src/shared/components/router/router.jsx
Labels: enhancement

#60 Docs : Readme
  README.md
  image.png
  package-lock.json
Labels: documentation

#63 Refactor : 내 일정(캘린더)
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ScheduleBar.jsx
Labels: refactor

#64 Refactor : refactor EmployeeList, Salary, SalaryAdmin
  package-lock.json
  package.json
  src/pages/employeeList/EmployeeList.jsx
  src/pages/employeeList/hooks/useEmployees.js
  src/pages/salary/Salary.jsx
  src/pages/salary/SalaryAdmin.jsx
  src/pages/salary/hooks/useAvailableMonths.js
  src/pages/salary/hooks/useRecalculateDeductions.js
  src/pages/salary/hooks/useSalaryData.js
  src/pages/salary/utils/recalculateDeductions.js
  src/shared/components/Input.jsx
Labels: refactor

#66 Refactor : 내 일정(캘린더)
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarBody.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ModalContent.jsx
  src/pages/calendar/components/ScheduleBar.jsx
  src/pages/calendar/hooks/useSchedules.js
Labels: refactor

#65 Refactor: SalaryAdjustment
  image.png
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/ManagerSelectBox.jsx
  src/pages/salaryAdjustment/components/SalaryHistoryModal.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/pages/salaryAdjustment/components/SalaryTable.jsx
  src/pages/salaryAdjustment/components/StatusCell.jsx
  src/pages/salaryAdjustment/components/TitleContainer.jsx
Labels: refactor

#62 Refactor : Login, Signup, SalaryAdjustment-Admin, Header
  .firebase/hosting.ZGlzdA.cache
  .gitignore
  src/App.jsx
  src/main.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/auth/components/auth-component.jsx
  src/pages/auth/constants/AUTH_ERRORS.js
  src/pages/auth/hooks/useLoginForm.js
  src/pages/auth/hooks/useSignupForm.js
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/pages/salaryAdjustment/components/SalaryTable.jsx
  src/pages/salaryAdjustment/components/TitleContainer.jsx
  src/pages/salaryAdjustment/util/formatYearMonth.js
  src/shared/Header/DispatchUserWrapper.jsx
  src/shared/Header/Header.jsx
  src/shared/Header/LogOutButton.jsx
  src/shared/Layout.jsx
Labels: refactor

#67 최종 리팩터링 버전
  .firebase/hosting.ZGlzdA.cache
  .gitignore
  image.png
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/Signup.jsx
  src/pages/auth/components/auth-component.jsx
  src/pages/auth/constants/AUTH_ERRORS.js
  src/pages/auth/hooks/useLoginForm.js
  src/pages/auth/hooks/useSignupForm.js
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/CalendarBody.jsx
  src/pages/calendar/components/LabelColor.jsx
  src/pages/calendar/components/ModalContent.jsx
  src/pages/calendar/components/ScheduleBar.jsx
  src/pages/calendar/hooks/useSchedules.js
  src/pages/employeeList/EmployeeList.jsx
  src/pages/employeeList/hooks/useEmployees.js
  src/pages/salary/Salary.jsx
  src/pages/salary/SalaryAdmin.jsx
  src/pages/salary/hooks/useAvailableMonths.js
  src/pages/salary/hooks/useRecalculateDeductions.js
  src/pages/salary/hooks/useSalaryData.js
  src/pages/salary/utils/recalculateDeductions.js
  src/pages/salaryAdjustment/SalaryAdjustment.jsx
  src/pages/salaryAdjustment/components/ManagerSelectBox.jsx
  src/pages/salaryAdjustment/components/SalaryHistoryModal.jsx
  src/pages/salaryAdjustment/components/SalaryManagementModal.jsx
  src/pages/salaryAdjustment/components/SalaryRegisterModal.jsx
  src/pages/salaryAdjustment/components/SalaryTable.jsx
  src/pages/salaryAdjustment/components/StatusCell.jsx
  src/pages/salaryAdjustment/components/TitleContainer.jsx
  src/pages/salaryAdjustment/util/formatYearMonth.js
  src/shared/Header/DispatchUserWrapper.jsx
  src/shared/Header/Header.jsx
  src/shared/Header/LogOutButton.jsx
  src/shared/Layout.jsx
  src/shared/components/Input.jsx
Labels: refactor
